### ISSUE TITLE
users#show (ActiveRecord::RecordNotFound) "ActiveRecord::RecordNotFound"

### ISSUE THREAD

**Issue by kugaevsky** [NNRUG/it52-rails#20]
<meta name="exception_notification_http">

<h2>ActiveRecord::RecordNotFound occurred in users</h2>

<pre>
ActiveRecord::RecordNotFound
app/controllers/users_controller.rb:10:in `show&#39;
</pre>

<h2>Request</h2>

<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://www.it52.info/users/-3ed2313c-9de5-4286-b812-f5bb37ad59d9</td></tr>
<tr><td>IP address</td><td>100.43.85.17</td></tr>
<tr><td>Parameters</td><td>{&quot;action&quot;=&gt;&quot;show&quot;, &quot;controller&quot;=&gt;&quot;users&quot;, &quot;id&quot;=&gt;&quot;-3ed2313c-9de5-4286-b812-f5bb37ad59d9&quot;}</td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2014-12-22 18:55:08 +0400</td></tr>
</table>

<h2>Session</h2>

<table class="table table-hover table-condensed">
<tr><td>session id</td><td>nil</td></tr>
<tr><td>data</td><td>#&lt;ActionDispatch::Request::Session:0x7f6b007c91c0 not yet loaded&gt;
</td></tr>
</table>

<h2>Environment</h2>

<table class="table table-hover table-condensed">
<tr><td>HTTP_ACCEPT</td><td>*/*</td></tr>
<tr><td>HTTP_ACCEPT_ENCODING</td><td>gzip,deflate</td></tr>
<tr><td>HTTP_ACCEPT_LANGUAGE</td><td>en-us, en;q=0.7, *;q=0.01</td></tr>
<tr><td>HTTP_CONNECTION</td><td>close</td></tr>
<tr><td>HTTP_CONNECT_TIME</td><td>2</td></tr>
<tr><td>HTTP_FROM</td><td>support@search.yandex.ru</td></tr>
<tr><td>HTTP_HOST</td><td>www.it52.info</td></tr>
<tr><td>HTTP_TOTAL_ROUTE_TIME</td><td>0</td></tr>
<tr><td>HTTP_USER_AGENT</td><td>Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)</td></tr>
<tr><td>HTTP_VERSION</td><td>HTTP/1.1</td></tr>
<tr><td>HTTP_VIA</td><td>1.1 vegur</td></tr>
<tr><td>HTTP_X_FORWARDED_FOR</td><td>100.43.85.17</td></tr>
<tr><td>HTTP_X_FORWARDED_PORT</td><td>80</td></tr>
<tr><td>HTTP_X_FORWARDED_PROTO</td><td>http</td></tr>
<tr><td>HTTP_X_REQUEST_ID</td><td>b9b24607-d1fe-451e-945d-fbc58af42601</td></tr>
<tr><td>HTTP_X_REQUEST_START</td><td>1419260108876</td></tr>
<tr><td>ORIGINAL_FULLPATH</td><td>/users/-3ed2313c-9de5-4286-b812-f5bb37ad59d9</td></tr>
<tr><td>ORIGINAL_SCRIPT_NAME</td><td></td></tr>
<tr><td>PATH_INFO</td><td>/users/-3ed2313c-9de5-4286-b812-f5bb37ad59d9</td></tr>
<tr><td>QUERY_STRING</td><td></td></tr>
<tr><td>REMOTE_ADDR</td><td>10.208.64.120</td></tr>
<tr><td>REQUEST_METHOD</td><td>GET</td></tr>
<tr><td>REQUEST_PATH</td><td>/users/-3ed2313c-9de5-4286-b812-f5bb37ad59d9</td></tr>
<tr><td>REQUEST_URI</td><td>/users/-3ed2313c-9de5-4286-b812-f5bb37ad59d9</td></tr>
<tr><td>ROUTES_70048721170960_SCRIPT_NAME</td><td></td></tr>
<tr><td>SCRIPT_NAME</td><td></td></tr>
<tr><td>SERVER_NAME</td><td>www.it52.info</td></tr>
<tr><td>SERVER_PORT</td><td>80</td></tr>
<tr><td>SERVER_PROTOCOL</td><td>HTTP/1.1</td></tr>
<tr><td>SERVER_SOFTWARE</td><td>Unicorn 4.8.3</td></tr>
<tr><td>action_controller.instance</td><td>users#show</td></tr>
<tr><td>action_dispatch.backtrace_cleaner</td><td>#&lt;Rails::BacktraceCleaner:0x007f6b0081bab0&gt;</td></tr>
<tr><td>action_dispatch.cookies</td><td>#&lt;ActionDispatch::Cookies::CookieJar:0x007f6b00804db0&gt;</td></tr>
<tr><td>action_dispatch.cookies_serializer</td><td>json</td></tr>
<tr><td>action_dispatch.encrypted_cookie_salt</td><td>encrypted cookie</td></tr>
<tr><td>action_dispatch.encrypted_signed_cookie_salt</td><td>signed encrypted cookie</td></tr>
<tr><td>action_dispatch.http_auth_salt</td><td>http authentication</td></tr>
<tr><td>action_dispatch.key_generator</td><td>#&lt;ActiveSupport::CachingKeyGenerator:0x007f6b0081b060&gt;</td></tr>
<tr><td>action_dispatch.logger</td><td>#&lt;Logger:0x007f6afbb282d0&gt;</td></tr>
<tr><td>action_dispatch.parameter_filter</td><td>[:password]</td></tr>
<tr><td>action_dispatch.redirect_filter</td><td>[]</td></tr>
<tr><td>action_dispatch.remote_ip</td><td>100.43.85.17</td></tr>
<tr><td>action_dispatch.request.accepts</td><td>[#&lt;Mime::Type:0x007f6b00cd9d40 @synonyms=[], @symbol=nil, @string=&quot;*/*&quot;&gt;]</td></tr>
<tr><td>action_dispatch.request.content_type</td><td></td></tr>
<tr><td>action_dispatch.request.formats</td><td>[#&lt;Mime::Type:0x007f6b00cd9d40 @synonyms=[], @symbol=nil, @string=&quot;*/*&quot;&gt;]</td></tr>
<tr><td>action_dispatch.request.parameters</td><td>{&quot;action&quot;=&gt;&quot;show&quot;, &quot;controller&quot;=&gt;&quot;users&quot;, &quot;id&quot;=&gt;&quot;-3ed2313c-9de5-4286-b812-f5bb37ad59d9&quot;}</td></tr>
<tr><td>action_dispatch.request.path_parameters</td><td>{:action=&gt;&quot;show&quot;, :controller=&gt;&quot;users&quot;, :id=&gt;&quot;-3ed2313c-9de5-4286-b812-f5bb37ad59d9&quot;}</td></tr>
<tr><td>action_dispatch.request.query_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.request_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.unsigned_session_cookie</td><td>{}</td></tr>
<tr><td>action_dispatch.request_id</td><td>b9b24607-d1fe-451e-945d-fbc58af42601</td></tr>
<tr><td>action_dispatch.routes</td><td>#&lt;ActionDispatch::Routing::RouteSet:0x007f6afa48e420&gt;</td></tr>
<tr><td>action_dispatch.secret_key_base</td><td>&lt;%= ENV[&#39;secret_key_base&#39;] =&gt;</td></tr>
<tr><td>action_dispatch.secret_token</td><td></td></tr>
<tr><td>action_dispatch.show_detailed_exceptions</td><td>false</td></tr>
<tr><td>action_dispatch.show_exceptions</td><td>true</td></tr>
<tr><td>action_dispatch.signed_cookie_salt</td><td>signed cookie</td></tr>
<tr><td>newrelic.agent_hooks_before_fired</td><td>true</td></tr>
<tr><td>newrelic.captured_request</td><td>true</td></tr>
<tr><td>rack.errors</td><td>#&lt;IO:0x007f6af9a85c08&gt;</td></tr>
<tr><td>rack.hijack</td><td>#&lt;Proc:0x007f6b007b9b30@/app/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_request.rb:111&gt;</td></tr>
<tr><td>rack.hijack?</td><td>true</td></tr>
<tr><td>rack.input</td><td>#&lt;StringIO:0x007f6afab5d198&gt;</td></tr>
<tr><td>rack.logger</td><td>#&lt;Logger:0x007f6afac12818&gt;</td></tr>
<tr><td>rack.multiprocess</td><td>true</td></tr>
<tr><td>rack.multithread</td><td>false</td></tr>
<tr><td>rack.request.cookie_hash</td><td>{}</td></tr>
<tr><td>rack.request.query_hash</td><td>{}</td></tr>
<tr><td>rack.request.query_string</td><td></td></tr>
<tr><td>rack.run_once</td><td>false</td></tr>
<tr><td>rack.session</td><td>#&lt;ActionDispatch::Request::Session:0x007f6b007c91c0&gt;</td></tr>
<tr><td>rack.session.options</td><td>#&lt;ActionDispatch::Request::Session::Options:0x007f6b007c9148&gt;</td></tr>
<tr><td>rack.url_scheme</td><td>http</td></tr>
<tr><td>rack.version</td><td>[1, 2]</td></tr>
<tr><td>warden</td><td>Warden::Proxy:70048773195300 @config={:default_scope=&gt;:user, :scope_defaults=&gt;{}, :default_strategies=&gt;{:user=&gt;[:rememberable, :database_authenticatable]}, :intercept_401=&gt;false, :failure_app=&gt;#&lt;Devise::Delegator:0x007f6b01473808&gt;}</td></tr>
<tr><td>Process</td><td>985</td></tr>
<tr><td>Server</td><td>5c66741a-d5f2-4a3e-ad9d-a86059e7c0b3</td></tr>
</table>

<h2>Backtrace</h2>

<pre>
app/controllers/users_controller.rb:10:in `show&#39;
</pre>

<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=5&above-color=red&below-color=gray&width=5&limits=0,5&d=0,0,1,4,5,2,5' alt='{"runtimeerror":["Jun 29",1,"Jun 30",4,"Jul 01",5,"Jul 02",2,"Jul 03",5]}' title='{"runtimeerror":["Jun 29",1,"Jun 30",4,"Jul 01",5,"Jul 02",2,"Jul 03",5]}'/>

**Comment by kugaevsky** [comment]
<meta name="exception_notification_http">

<h2>ActiveRecord::RecordNotFound occurred in users</h2>

<pre>
ActiveRecord::RecordNotFound
app/controllers/users_controller.rb:10:in `show&#39;
</pre>

<h2>Request</h2>

<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://www.it52.info/users/-2f0164e1-b139-466d-abe7-76dcd656df5a</td></tr>
<tr><td>IP address</td><td>100.43.91.10</td></tr>
<tr><td>Parameters</td><td>{&quot;action&quot;=&gt;&quot;show&quot;, &quot;controller&quot;=&gt;&quot;users&quot;, &quot;id&quot;=&gt;&quot;-2f0164e1-b139-466d-abe7-76dcd656df5a&quot;}</td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-02-12 19:03:26 +0300</td></tr>
</table>

<h2>Session</h2>

<table class="table table-hover table-condensed">
<tr><td>session id</td><td>nil</td></tr>
<tr><td>data</td><td>#&lt;ActionDispatch::Request::Session:0x7fb275ab01b0 not yet loaded&gt;
</td></tr>
</table>

<h2>Environment</h2>

<table class="table table-hover table-condensed">
<tr><td>HTTP_ACCEPT</td><td>*/*</td></tr>
<tr><td>HTTP_ACCEPT_ENCODING</td><td>gzip,deflate</td></tr>
<tr><td>HTTP_ACCEPT_LANGUAGE</td><td>en-us, en;q=0.7, *;q=0.01</td></tr>
<tr><td>HTTP_CONNECTION</td><td>close</td></tr>
<tr><td>HTTP_CONNECT_TIME</td><td>0</td></tr>
<tr><td>HTTP_FROM</td><td>support@search.yandex.ru</td></tr>
<tr><td>HTTP_HOST</td><td>www.it52.info</td></tr>
<tr><td>HTTP_TOTAL_ROUTE_TIME</td><td>0</td></tr>
<tr><td>HTTP_USER_AGENT</td><td>Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)</td></tr>
<tr><td>HTTP_VERSION</td><td>HTTP/1.1</td></tr>
<tr><td>HTTP_VIA</td><td>1.1 vegur</td></tr>
<tr><td>HTTP_X_FORWARDED_FOR</td><td>100.43.91.10</td></tr>
<tr><td>HTTP_X_FORWARDED_PORT</td><td>80</td></tr>
<tr><td>HTTP_X_FORWARDED_PROTO</td><td>http</td></tr>
<tr><td>HTTP_X_REQUEST_ID</td><td>a671394a-68c2-46c1-bad5-eda6b079985e</td></tr>
<tr><td>HTTP_X_REQUEST_START</td><td>1423757006128</td></tr>
<tr><td>ORIGINAL_FULLPATH</td><td>/users/-2f0164e1-b139-466d-abe7-76dcd656df5a</td></tr>
<tr><td>ORIGINAL_SCRIPT_NAME</td><td></td></tr>
<tr><td>PATH_INFO</td><td>/users/-2f0164e1-b139-466d-abe7-76dcd656df5a</td></tr>
<tr><td>QUERY_STRING</td><td></td></tr>
<tr><td>REMOTE_ADDR</td><td>10.37.150.183</td></tr>
<tr><td>REQUEST_METHOD</td><td>GET</td></tr>
<tr><td>REQUEST_PATH</td><td>/users/-2f0164e1-b139-466d-abe7-76dcd656df5a</td></tr>
<tr><td>REQUEST_URI</td><td>/users/-2f0164e1-b139-466d-abe7-76dcd656df5a</td></tr>
<tr><td>ROUTES_70202231126360_SCRIPT_NAME</td><td></td></tr>
<tr><td>SCRIPT_NAME</td><td></td></tr>
<tr><td>SERVER_NAME</td><td>www.it52.info</td></tr>
<tr><td>SERVER_PORT</td><td>80</td></tr>
<tr><td>SERVER_PROTOCOL</td><td>HTTP/1.1</td></tr>
<tr><td>SERVER_SOFTWARE</td><td>Unicorn 4.8.3</td></tr>
<tr><td>action_controller.instance</td><td>users#show</td></tr>
<tr><td>action_dispatch.backtrace_cleaner</td><td>#&lt;Rails::BacktraceCleaner:0x007fb274305970&gt;</td></tr>
<tr><td>action_dispatch.cookies</td><td>#&lt;ActionDispatch::Cookies::CookieJar:0x007fb275a66bf0&gt;</td></tr>
<tr><td>action_dispatch.cookies_serializer</td><td>json</td></tr>
<tr><td>action_dispatch.encrypted_cookie_salt</td><td>encrypted cookie</td></tr>
<tr><td>action_dispatch.encrypted_signed_cookie_salt</td><td>signed encrypted cookie</td></tr>
<tr><td>action_dispatch.http_auth_salt</td><td>http authentication</td></tr>
<tr><td>action_dispatch.key_generator</td><td>#&lt;ActiveSupport::CachingKeyGenerator:0x007fb274305088&gt;</td></tr>
<tr><td>action_dispatch.logger</td><td>#&lt;Logger:0x007fb27604fdf0&gt;</td></tr>
<tr><td>action_dispatch.parameter_filter</td><td>[:password]</td></tr>
<tr><td>action_dispatch.redirect_filter</td><td>[]</td></tr>
<tr><td>action_dispatch.remote_ip</td><td>100.43.91.10</td></tr>
<tr><td>action_dispatch.request.accepts</td><td>[#&lt;Mime::Type:0x007fb276ff93c8 @synonyms=[], @symbol=nil, @string=&quot;*/*&quot;&gt;]</td></tr>
<tr><td>action_dispatch.request.content_type</td><td></td></tr>
<tr><td>action_dispatch.request.formats</td><td>[#&lt;Mime::Type:0x007fb276ff93c8 @synonyms=[], @symbol=nil, @string=&quot;*/*&quot;&gt;]</td></tr>
<tr><td>action_dispatch.request.parameters</td><td>{&quot;action&quot;=&gt;&quot;show&quot;, &quot;controller&quot;=&gt;&quot;users&quot;, &quot;id&quot;=&gt;&quot;-2f0164e1-b139-466d-abe7-76dcd656df5a&quot;}</td></tr>
<tr><td>action_dispatch.request.path_parameters</td><td>{:action=&gt;&quot;show&quot;, :controller=&gt;&quot;users&quot;, :id=&gt;&quot;-2f0164e1-b139-466d-abe7-76dcd656df5a&quot;}</td></tr>
<tr><td>action_dispatch.request.query_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.request_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.unsigned_session_cookie</td><td>{}</td></tr>
<tr><td>action_dispatch.request_id</td><td>a671394a-68c2-46c1-bad5-eda6b079985e</td></tr>
<tr><td>action_dispatch.routes</td><td>#&lt;ActionDispatch::Routing::RouteSet:0x007fb27618f2b0&gt;</td></tr>
<tr><td>action_dispatch.secret_key_base</td><td>&lt;%= ENV[&#39;secret_key_base&#39;] =&gt;</td></tr>
<tr><td>action_dispatch.secret_token</td><td></td></tr>
<tr><td>action_dispatch.show_detailed_exceptions</td><td>false</td></tr>
<tr><td>action_dispatch.show_exceptions</td><td>true</td></tr>
<tr><td>action_dispatch.signed_cookie_salt</td><td>signed cookie</td></tr>
<tr><td>newrelic.agent_hooks_before_fired</td><td>true</td></tr>
<tr><td>newrelic.captured_request</td><td>true</td></tr>
<tr><td>rack.errors</td><td>#&lt;IO:0x007fb270c45548&gt;</td></tr>
<tr><td>rack.hijack</td><td>#&lt;Proc:0x007fb275ab4440@/app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_request.rb:111&gt;</td></tr>
<tr><td>rack.hijack?</td><td>true</td></tr>
<tr><td>rack.input</td><td>#&lt;StringIO:0x007fb271a28890&gt;</td></tr>
<tr><td>rack.logger</td><td>#&lt;Logger:0x007fb271964940&gt;</td></tr>
<tr><td>rack.multiprocess</td><td>true</td></tr>
<tr><td>rack.multithread</td><td>false</td></tr>
<tr><td>rack.request.cookie_hash</td><td>{}</td></tr>
<tr><td>rack.request.query_hash</td><td>{}</td></tr>
<tr><td>rack.request.query_string</td><td></td></tr>
<tr><td>rack.run_once</td><td>false</td></tr>
<tr><td>rack.session</td><td>#&lt;ActionDispatch::Request::Session:0x007fb275ab01b0&gt;</td></tr>
<tr><td>rack.session.options</td><td>#&lt;ActionDispatch::Request::Session::Options:0x007fb275ab0160&gt;</td></tr>
<tr><td>rack.url_scheme</td><td>http</td></tr>
<tr><td>rack.version</td><td>[1, 2]</td></tr>
<tr><td>warden</td><td>Warden::Proxy:70202227505680 @config={:default_scope=&gt;:user, :scope_defaults=&gt;{}, :default_strategies=&gt;{:user=&gt;[:rememberable, :database_authenticatable]}, :intercept_401=&gt;false, :failure_app=&gt;#&lt;Devise::Delegator:0x007fb2767edbe8&gt;}</td></tr>
<tr><td>Process</td><td>8</td></tr>
<tr><td>Server</td><td>782c1d0d-49f9-4057-a955-56aae0156a24</td></tr>
</table>

<h2>Backtrace</h2>

<pre>
app/controllers/users_controller.rb:10:in `show&#39;
</pre>

<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Feb 12",1]}' title='{"runtimeerror":["Feb 12",1]}'/>

**Comment by kugaevsky** [comment]
<meta name="exception_notification_http">

<h2>ActiveRecord::RecordNotFound occurred in users</h2>

<pre>
ActiveRecord::RecordNotFound
app/controllers/users_controller.rb:10:in `show&#39;
</pre>

<h2>Request</h2>

<table class="table table-hover table-condensed">
<tr><td>URL</td><td>https://www.it52.info/users/michaelle-mail-ru</td></tr>
<tr><td>IP address</td><td>207.46.13.141</td></tr>
<tr><td>Parameters</td><td>{&quot;controller&quot;=&gt;&quot;users&quot;, &quot;action&quot;=&gt;&quot;show&quot;, &quot;id&quot;=&gt;&quot;michaelle-mail-ru&quot;}</td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2016-06-26 10:29:02 +0300</td></tr>
</table>

<h2>Session</h2>

<table class="table table-hover table-condensed">
<tr><td>session id</td><td>[FILTERED]</td></tr>
<tr><td>data</td><td>#&lt;ActionDispatch::Request::Session:0x7fc628be4cb8 not yet loaded&gt;
</td></tr>
</table>

<h2>Environment</h2>

<table class="table table-hover table-condensed">
<tr><td>HTTP_ACCEPT</td><td>*/*</td></tr>
<tr><td>HTTP_ACCEPT_ENCODING</td><td>gzip, deflate</td></tr>
<tr><td>HTTP_CACHE_CONTROL</td><td>no-cache</td></tr>
<tr><td>HTTP_CONNECTION</td><td>close</td></tr>
<tr><td>HTTP_CONNECT_TIME</td><td>0</td></tr>
<tr><td>HTTP_FROM</td><td>bingbot(at)microsoft.com</td></tr>
<tr><td>HTTP_HOST</td><td>www.it52.info</td></tr>
<tr><td>HTTP_PRAGMA</td><td>no-cache</td></tr>
<tr><td>HTTP_TOTAL_ROUTE_TIME</td><td>0</td></tr>
<tr><td>HTTP_USER_AGENT</td><td>Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)</td></tr>
<tr><td>HTTP_VERSION</td><td>HTTP/1.1</td></tr>
<tr><td>HTTP_VIA</td><td>1.1 vegur</td></tr>
<tr><td>HTTP_X_FORWARDED_FOR</td><td>207.46.13.141</td></tr>
<tr><td>HTTP_X_FORWARDED_PORT</td><td>443</td></tr>
<tr><td>HTTP_X_FORWARDED_PROTO</td><td>https</td></tr>
<tr><td>HTTP_X_REQUEST_ID</td><td>a47465aa-17a0-4715-a865-5216b20604d6</td></tr>
<tr><td>HTTP_X_REQUEST_START</td><td>1466926142653</td></tr>
<tr><td>ORIGINAL_FULLPATH</td><td>/users/michaelle-mail-ru</td></tr>
<tr><td>ORIGINAL_SCRIPT_NAME</td><td></td></tr>
<tr><td>PATH_INFO</td><td>/users/michaelle-mail-ru</td></tr>
<tr><td>QUERY_STRING</td><td></td></tr>
<tr><td>REMOTE_ADDR</td><td>10.83.24.250</td></tr>
<tr><td>REQUEST_METHOD</td><td>GET</td></tr>
<tr><td>REQUEST_PATH</td><td>/users/michaelle-mail-ru</td></tr>
<tr><td>REQUEST_URI</td><td>/users/michaelle-mail-ru</td></tr>
<tr><td>ROUTES_70244506346100_SCRIPT_NAME</td><td></td></tr>
<tr><td>SCRIPT_NAME</td><td></td></tr>
<tr><td>SERVER_NAME</td><td>www.it52.info</td></tr>
<tr><td>SERVER_PORT</td><td>443</td></tr>
<tr><td>SERVER_PROTOCOL</td><td>HTTP/1.1</td></tr>
<tr><td>SERVER_SOFTWARE</td><td>Unicorn 5.1.0</td></tr>
<tr><td>action_controller.instance</td><td>users#show</td></tr>
<tr><td>action_dispatch.backtrace_cleaner</td><td>#&lt;Rails::BacktraceCleaner:0x007fc623cdb680&gt;</td></tr>
<tr><td>action_dispatch.cookies</td><td>#&lt;ActionDispatch::Cookies::CookieJar:0x007fc627dd91a0&gt;</td></tr>
<tr><td>action_dispatch.cookies_digest</td><td></td></tr>
<tr><td>action_dispatch.cookies_serializer</td><td>json</td></tr>
<tr><td>action_dispatch.encrypted_cookie_salt</td><td>encrypted cookie</td></tr>
<tr><td>action_dispatch.encrypted_signed_cookie_salt</td><td>signed encrypted cookie</td></tr>
<tr><td>action_dispatch.http_auth_salt</td><td>http authentication</td></tr>
<tr><td>action_dispatch.key_generator</td><td>#&lt;ActiveSupport::CachingKeyGenerator:0x007fc625b999a0&gt;</td></tr>
<tr><td>action_dispatch.logger</td><td>#&lt;RailsStdoutLogging::StdoutLogger:0x007fc62687e260&gt;</td></tr>
<tr><td>action_dispatch.parameter_filter</td><td>[:password]</td></tr>
<tr><td>action_dispatch.redirect_filter</td><td>[]</td></tr>
<tr><td>action_dispatch.remote_ip</td><td>207.46.13.141</td></tr>
<tr><td>action_dispatch.request.accepts</td><td>[#&lt;Mime::Type:0x007fc627dda938 @synonyms=[], @symbol=nil, @string=&quot;*/*&quot;, @hash=1351029308960328727&gt;]</td></tr>
<tr><td>action_dispatch.request.content_type</td><td></td></tr>
<tr><td>action_dispatch.request.formats</td><td>[#&lt;Mime::Type:0x007fc627dda938 @synonyms=[], @symbol=nil, @string=&quot;*/*&quot;, @hash=1351029308960328727&gt;]</td></tr>
<tr><td>action_dispatch.request.parameters</td><td>{&quot;controller&quot;=&gt;&quot;users&quot;, &quot;action&quot;=&gt;&quot;show&quot;, &quot;id&quot;=&gt;&quot;michaelle-mail-ru&quot;}</td></tr>
<tr><td>action_dispatch.request.path_parameters</td><td>{:controller=&gt;&quot;users&quot;, :action=&gt;&quot;show&quot;, :id=&gt;&quot;michaelle-mail-ru&quot;}</td></tr>
<tr><td>action_dispatch.request.query_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.request_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.unsigned_session_cookie</td><td>{}</td></tr>
<tr><td>action_dispatch.request_id</td><td>a47465aa-17a0-4715-a865-5216b20604d6</td></tr>
<tr><td>action_dispatch.routes</td><td>#&lt;ActionDispatch::Routing::RouteSet:0x007fc625b244e8&gt;</td></tr>
<tr><td>action_dispatch.secret_key_base</td><td>&lt;%= ENV[&#39;secret_key_base&#39;] =&gt;</td></tr>
<tr><td>action_dispatch.secret_token</td><td></td></tr>
<tr><td>action_dispatch.show_detailed_exceptions</td><td>false</td></tr>
<tr><td>action_dispatch.show_exceptions</td><td>true</td></tr>
<tr><td>action_dispatch.signed_cookie_salt</td><td>signed cookie</td></tr>
<tr><td>newrelic.transaction_started</td><td>true</td></tr>
<tr><td>rack.errors</td><td>#&lt;IO:0x007fc62119db08&gt;</td></tr>
<tr><td>rack.hijack</td><td>#&lt;Unicorn::HttpParser:0x007fc621c17278&gt;</td></tr>
<tr><td>rack.hijack?</td><td>true</td></tr>
<tr><td>rack.input</td><td>#&lt;StringIO:0x007fc621e9bf30&gt;</td></tr>
<tr><td>rack.logger</td><td>#&lt;Logger:0x007fc621dba418&gt;</td></tr>
<tr><td>rack.multiprocess</td><td>true</td></tr>
<tr><td>rack.multithread</td><td>false</td></tr>
<tr><td>rack.request.cookie_hash</td><td>{}</td></tr>
<tr><td>rack.request.query_hash</td><td>{}</td></tr>
<tr><td>rack.request.query_string</td><td></td></tr>
<tr><td>rack.run_once</td><td>false</td></tr>
<tr><td>rack.session</td><td>#&lt;ActionDispatch::Request::Session:0x007fc628be4cb8&gt;</td></tr>
<tr><td>rack.session.options</td><td>#&lt;ActionDispatch::Request::Session::Options:0x007fc628be4c68&gt;</td></tr>
<tr><td>rack.url_scheme</td><td>https</td></tr>
<tr><td>rack.version</td><td>[1, 2]</td></tr>
<tr><td>unicorn.socket</td><td>#&lt;Kgio::Socket:0x007fc6291c5088&gt;</td></tr>
<tr><td>warden</td><td>Warden::Proxy:70244531905760 @config={:default_scope=&gt;:user, :scope_defaults=&gt;{}, :default_strategies=&gt;{:user=&gt;[:rememberable, :database_authenticatable]}, :intercept_401=&gt;false, :failure_app=&gt;#&lt;Devise::Delegator:0x007fc625b98c08&gt;}</td></tr>
<tr><td>Process</td><td>6</td></tr>
<tr><td>Server</td><td>5e041d9c-8e64-4c2f-b48d-c0f79a6f841a</td></tr>
</table>

<h2>Backtrace</h2>

<pre>
app/controllers/users_controller.rb:10:in `show&#39;
</pre>

<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Jun 26",1]}' title='{"runtimeerror":["Jun 26",1]}'/>
