### ISSUE TITLE
events#index (NoMethodError) "undefined method `updated_at' for nil:NilClass"

### ISSUE THREAD

**Issue by kugaevsky** [NNRUG/it52-rails#21]
<meta name="exception_notification_http">

<h2>NoMethodError occurred in events</h2>

<pre>
undefined method `updated_at&#39; for nil:NilClass
app/views/events/index.atom.builder:6:in `block in _app_views_events_index_atom_builder___4192425350072697163_70074729398040&#39;
</pre>

<h2>Request</h2>

<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://www.it52.info/events.atom</td></tr>
<tr><td>IP address</td><td>65.19.138.34</td></tr>
<tr><td>Parameters</td><td>{&quot;action&quot;=&gt;&quot;index&quot;, &quot;controller&quot;=&gt;&quot;events&quot;, &quot;format&quot;=&gt;&quot;atom&quot;}</td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2014-12-26 04:23:08 +0400</td></tr>
</table>

<h2>Session</h2>

<table class="table table-hover table-condensed">
<tr><td>session id</td><td>nil</td></tr>
<tr><td>data</td><td>#&lt;ActionDispatch::Request::Session:0x7f7718f91820 not yet loaded&gt;
</td></tr>
</table>

<h2>Environment</h2>

<table class="table table-hover table-condensed">
<tr><td>HTTP_ACCEPT</td><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr>
<tr><td>HTTP_ACCEPT_CHARSET</td><td>ISO-8859-1,utf-8;q=0.7,*;q=0.3</td></tr>
<tr><td>HTTP_ACCEPT_ENCODING</td><td>gzip,deflate</td></tr>
<tr><td>HTTP_CONNECTION</td><td>close</td></tr>
<tr><td>HTTP_CONNECT_TIME</td><td>1</td></tr>
<tr><td>HTTP_FROM</td><td>feeds@feedly.com</td></tr>
<tr><td>HTTP_HOST</td><td>www.it52.info</td></tr>
<tr><td>HTTP_IF_NONE_MATCH</td><td>&quot;62acabbc118ac25cfc101ee8c2256b8f&quot;</td></tr>
<tr><td>HTTP_TOTAL_ROUTE_TIME</td><td>0</td></tr>
<tr><td>HTTP_USER_AGENT</td><td>Feedly/1.0 (+http://www.feedly.com/fetcher.html; like FeedFetcher-Google)</td></tr>
<tr><td>HTTP_VERSION</td><td>HTTP/1.1</td></tr>
<tr><td>HTTP_VIA</td><td>1.1 vegur</td></tr>
<tr><td>HTTP_X_FORWARDED_FOR</td><td>65.19.138.34</td></tr>
<tr><td>HTTP_X_FORWARDED_PORT</td><td>80</td></tr>
<tr><td>HTTP_X_FORWARDED_PROTO</td><td>http</td></tr>
<tr><td>HTTP_X_REQUEST_ID</td><td>482f0040-be4d-48fb-b078-61b2f6c89b4b</td></tr>
<tr><td>HTTP_X_REQUEST_START</td><td>1419553388602</td></tr>
<tr><td>ORIGINAL_FULLPATH</td><td>/events.atom</td></tr>
<tr><td>ORIGINAL_SCRIPT_NAME</td><td></td></tr>
<tr><td>PATH_INFO</td><td>/events.atom</td></tr>
<tr><td>QUERY_STRING</td><td></td></tr>
<tr><td>REMOTE_ADDR</td><td>10.87.14.210</td></tr>
<tr><td>REQUEST_METHOD</td><td>GET</td></tr>
<tr><td>REQUEST_PATH</td><td>/events.atom</td></tr>
<tr><td>REQUEST_URI</td><td>/events.atom</td></tr>
<tr><td>ROUTES_70074703404400_SCRIPT_NAME</td><td></td></tr>
<tr><td>SCRIPT_NAME</td><td></td></tr>
<tr><td>SERVER_NAME</td><td>www.it52.info</td></tr>
<tr><td>SERVER_PORT</td><td>80</td></tr>
<tr><td>SERVER_PROTOCOL</td><td>HTTP/1.1</td></tr>
<tr><td>SERVER_SOFTWARE</td><td>Unicorn 4.8.3</td></tr>
<tr><td>action_controller.instance</td><td>events#index</td></tr>
<tr><td>action_dispatch.backtrace_cleaner</td><td>#&lt;Rails::BacktraceCleaner:0x007f7719713760&gt;</td></tr>
<tr><td>action_dispatch.cookies</td><td>#&lt;ActionDispatch::Cookies::CookieJar:0x007f7718f445e8&gt;</td></tr>
<tr><td>action_dispatch.cookies_serializer</td><td>json</td></tr>
<tr><td>action_dispatch.encrypted_cookie_salt</td><td>encrypted cookie</td></tr>
<tr><td>action_dispatch.encrypted_signed_cookie_salt</td><td>signed encrypted cookie</td></tr>
<tr><td>action_dispatch.http_auth_salt</td><td>http authentication</td></tr>
<tr><td>action_dispatch.key_generator</td><td>#&lt;ActiveSupport::CachingKeyGenerator:0x007f7719712db0&gt;</td></tr>
<tr><td>action_dispatch.logger</td><td>#&lt;Logger:0x007f7714d24bb8&gt;</td></tr>
<tr><td>action_dispatch.parameter_filter</td><td>[:password]</td></tr>
<tr><td>action_dispatch.redirect_filter</td><td>[]</td></tr>
<tr><td>action_dispatch.remote_ip</td><td>65.19.138.34</td></tr>
<tr><td>action_dispatch.request.content_type</td><td></td></tr>
<tr><td>action_dispatch.request.formats</td><td>[#&lt;Mime::Type:0x007f7714d3c2e0 @synonyms=[], @symbol=:atom, @string=&quot;application/atom+xml&quot;&gt;]</td></tr>
<tr><td>action_dispatch.request.parameters</td><td>{&quot;action&quot;=&gt;&quot;index&quot;, &quot;controller&quot;=&gt;&quot;events&quot;, &quot;format&quot;=&gt;&quot;atom&quot;}</td></tr>
<tr><td>action_dispatch.request.path_parameters</td><td>{:action=&gt;&quot;index&quot;, :controller=&gt;&quot;events&quot;, :format=&gt;&quot;atom&quot;}</td></tr>
<tr><td>action_dispatch.request.query_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.request_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.unsigned_session_cookie</td><td>{}</td></tr>
<tr><td>action_dispatch.request_id</td><td>482f0040-be4d-48fb-b078-61b2f6c89b4b</td></tr>
<tr><td>action_dispatch.routes</td><td>#&lt;ActionDispatch::Routing::RouteSet:0x007f77139bbae0&gt;</td></tr>
<tr><td>action_dispatch.secret_key_base</td><td>&lt;%= ENV[&#39;secret_key_base&#39;] =&gt;</td></tr>
<tr><td>action_dispatch.secret_token</td><td></td></tr>
<tr><td>action_dispatch.show_detailed_exceptions</td><td>false</td></tr>
<tr><td>action_dispatch.show_exceptions</td><td>true</td></tr>
<tr><td>action_dispatch.signed_cookie_salt</td><td>signed cookie</td></tr>
<tr><td>newrelic.agent_hooks_before_fired</td><td>true</td></tr>
<tr><td>newrelic.captured_request</td><td>true</td></tr>
<tr><td>rack.errors</td><td>#&lt;IO:0x007f7712999bf8&gt;</td></tr>
<tr><td>rack.hijack</td><td>#&lt;Proc:0x007f7718fa28a0@/app/vendor/bundle/ruby/2.1.0/gems/unicorn-4.8.3/lib/unicorn/http_request.rb:111&gt;</td></tr>
<tr><td>rack.hijack?</td><td>true</td></tr>
<tr><td>rack.input</td><td>#&lt;StringIO:0x007f7713a81cb8&gt;</td></tr>
<tr><td>rack.logger</td><td>#&lt;Logger:0x007f7713b3b2d0&gt;</td></tr>
<tr><td>rack.multiprocess</td><td>true</td></tr>
<tr><td>rack.multithread</td><td>false</td></tr>
<tr><td>rack.request.cookie_hash</td><td>{}</td></tr>
<tr><td>rack.request.query_hash</td><td>{}</td></tr>
<tr><td>rack.request.query_string</td><td></td></tr>
<tr><td>rack.run_once</td><td>false</td></tr>
<tr><td>rack.session</td><td>#&lt;ActionDispatch::Request::Session:0x007f7718f91820&gt;</td></tr>
<tr><td>rack.session.options</td><td>#&lt;ActionDispatch::Request::Session::Options:0x007f7718f917d0&gt;</td></tr>
<tr><td>rack.url_scheme</td><td>http</td></tr>
<tr><td>rack.version</td><td>[1, 2]</td></tr>
<tr><td>warden</td><td>Warden::Proxy:70074748406000 @config={:default_scope=&gt;:user, :scope_defaults=&gt;{}, :default_strategies=&gt;{:user=&gt;[:rememberable, :database_authenticatable]}, :intercept_401=&gt;false, :failure_app=&gt;#&lt;Devise::Delegator:0x007f771ab8dd80&gt;}</td></tr>
<tr><td>Process</td><td>8</td></tr>
<tr><td>Server</td><td>06c5b6e8-b43d-4699-86f8-05f95c79b47d</td></tr>
</table>

<h2>Backtrace</h2>

<pre>
app/views/events/index.atom.builder:6:in `block in _app_views_events_index_atom_builder___4192425350072697163_70074729398040&#39;
app/views/events/index.atom.builder:1:in `_app_views_events_index_atom_builder___4192425350072697163_70074729398040&#39;
app/controllers/events_controller.rb:19:in `index&#39;
</pre>

<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=17&above-color=red&below-color=gray&width=5&limits=0,17&d=17,9,10,6,2,4,13' alt='{"runtimeerror":["Jul 21",17,"Jul 22",9,"Jul 23",10,"Jul 24",6,"Jul 25",2,"Jul 26",4,"Jul 27",13]}' title='{"runtimeerror":["Jul 21",17,"Jul 22",9,"Jul 23",10,"Jul 24",6,"Jul 25",2,"Jul 26",4,"Jul 27",13]}'/>

**Comment by kugaevsky** [comment]
<meta name="exception_notification_http">

<h2>NoMethodError occurred in events</h2>

<pre>
undefined method `updated_at&#39; for nil:NilClass
app/views/events/index.atom.builder:6:in `block in _app_views_events_index_atom_builder___543000240874566235_70190644209100&#39;
</pre>

<h2>Request</h2>

<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://www.it52.info/events.atom</td></tr>
<tr><td>IP address</td><td>65.19.138.33</td></tr>
<tr><td>Parameters</td><td>{&quot;action&quot;=&gt;&quot;index&quot;, &quot;controller&quot;=&gt;&quot;events&quot;, &quot;format&quot;=&gt;&quot;atom&quot;}</td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-03-28 03:18:21 +0300</td></tr>
</table>

<h2>Session</h2>

<table class="table table-hover table-condensed">
<tr><td>session id</td><td>nil</td></tr>
<tr><td>data</td><td>#&lt;ActionDispatch::Request::Session:0x7fad10e3df18 not yet loaded&gt;
</td></tr>
</table>

<h2>Environment</h2>

<table class="table table-hover table-condensed">
<tr><td>HTTP_ACCEPT</td><td>text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8</td></tr>
<tr><td>HTTP_ACCEPT_CHARSET</td><td>ISO-8859-1,utf-8;q=0.7,*;q=0.3</td></tr>
<tr><td>HTTP_ACCEPT_ENCODING</td><td>gzip,deflate</td></tr>
<tr><td>HTTP_CONNECTION</td><td>close</td></tr>
<tr><td>HTTP_CONNECT_TIME</td><td>0</td></tr>
<tr><td>HTTP_FROM</td><td>feeds@feedly.com</td></tr>
<tr><td>HTTP_HOST</td><td>www.it52.info</td></tr>
<tr><td>HTTP_IF_NONE_MATCH</td><td>&quot;2bd42775c7b20dbd39113a183fb3e6c4&quot;</td></tr>
<tr><td>HTTP_TOTAL_ROUTE_TIME</td><td>0</td></tr>
<tr><td>HTTP_USER_AGENT</td><td>Feedly/1.0 (+http://www.feedly.com/fetcher.html; like FeedFetcher-Google)</td></tr>
<tr><td>HTTP_VERSION</td><td>HTTP/1.1</td></tr>
<tr><td>HTTP_VIA</td><td>1.1 vegur</td></tr>
<tr><td>HTTP_X_FORWARDED_FOR</td><td>65.19.138.33</td></tr>
<tr><td>HTTP_X_FORWARDED_PORT</td><td>80</td></tr>
<tr><td>HTTP_X_FORWARDED_PROTO</td><td>http</td></tr>
<tr><td>HTTP_X_REQUEST_ID</td><td>8eaee19e-52e1-4610-a204-81aee323860e</td></tr>
<tr><td>HTTP_X_REQUEST_START</td><td>1427501901282</td></tr>
<tr><td>ORIGINAL_FULLPATH</td><td>/events.atom</td></tr>
<tr><td>ORIGINAL_SCRIPT_NAME</td><td></td></tr>
<tr><td>PATH_INFO</td><td>/events.atom</td></tr>
<tr><td>QUERY_STRING</td><td></td></tr>
<tr><td>REMOTE_ADDR</td><td>10.79.129.18</td></tr>
<tr><td>REQUEST_METHOD</td><td>GET</td></tr>
<tr><td>REQUEST_PATH</td><td>/events.atom</td></tr>
<tr><td>REQUEST_URI</td><td>/events.atom</td></tr>
<tr><td>ROUTES_70190642278060_SCRIPT_NAME</td><td></td></tr>
<tr><td>SCRIPT_NAME</td><td></td></tr>
<tr><td>SERVER_NAME</td><td>www.it52.info</td></tr>
<tr><td>SERVER_PORT</td><td>80</td></tr>
<tr><td>SERVER_PROTOCOL</td><td>HTTP/1.1</td></tr>
<tr><td>SERVER_SOFTWARE</td><td>Unicorn 4.8.3</td></tr>
<tr><td>action_controller.instance</td><td>events#index</td></tr>
<tr><td>action_dispatch.backtrace_cleaner</td><td>#&lt;Rails::BacktraceCleaner:0x007fad0e96c298&gt;</td></tr>
<tr><td>action_dispatch.cookies</td><td>#&lt;ActionDispatch::Cookies::CookieJar:0x007fad10df9ed0&gt;</td></tr>
<tr><td>action_dispatch.cookies_serializer</td><td>json</td></tr>
<tr><td>action_dispatch.encrypted_cookie_salt</td><td>encrypted cookie</td></tr>
<tr><td>action_dispatch.encrypted_signed_cookie_salt</td><td>signed encrypted cookie</td></tr>
<tr><td>action_dispatch.http_auth_salt</td><td>http authentication</td></tr>
<tr><td>action_dispatch.key_generator</td><td>#&lt;ActiveSupport::CachingKeyGenerator:0x007fad0e9670e0&gt;</td></tr>
<tr><td>action_dispatch.logger</td><td>#&lt;Logger:0x007fad10850218&gt;</td></tr>
<tr><td>action_dispatch.parameter_filter</td><td>[:password]</td></tr>
<tr><td>action_dispatch.redirect_filter</td><td>[]</td></tr>
<tr><td>action_dispatch.remote_ip</td><td>65.19.138.33</td></tr>
<tr><td>action_dispatch.request.content_type</td><td></td></tr>
<tr><td>action_dispatch.request.formats</td><td>[#&lt;Mime::Type:0x007fad0cdc7d80 @synonyms=[], @symbol=:atom, @string=&quot;application/atom+xml&quot;&gt;]</td></tr>
<tr><td>action_dispatch.request.parameters</td><td>{&quot;action&quot;=&gt;&quot;index&quot;, &quot;controller&quot;=&gt;&quot;events&quot;, &quot;format&quot;=&gt;&quot;atom&quot;}</td></tr>
<tr><td>action_dispatch.request.path_parameters</td><td>{:action=&gt;&quot;index&quot;, :controller=&gt;&quot;events&quot;, :format=&gt;&quot;atom&quot;}</td></tr>
<tr><td>action_dispatch.request.query_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.request_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.unsigned_session_cookie</td><td>{}</td></tr>
<tr><td>action_dispatch.request_id</td><td>8eaee19e-52e1-4610-a204-81aee323860e</td></tr>
<tr><td>action_dispatch.routes</td><td>#&lt;ActionDispatch::Routing::RouteSet:0x007fad10995d58&gt;</td></tr>
<tr><td>action_dispatch.secret_key_base</td><td>&lt;%= ENV[&#39;secret_key_base&#39;] =&gt;</td></tr>
<tr><td>action_dispatch.secret_token</td><td></td></tr>
<tr><td>action_dispatch.show_detailed_exceptions</td><td>false</td></tr>
<tr><td>action_dispatch.show_exceptions</td><td>true</td></tr>
<tr><td>action_dispatch.signed_cookie_salt</td><td>signed cookie</td></tr>
<tr><td>newrelic.transaction_started</td><td>true</td></tr>
<tr><td>rack.errors</td><td>#&lt;IO:0x007fad0b4ad548&gt;</td></tr>
<tr><td>rack.hijack</td><td>#&lt;Proc:0x007fad10e417d0@/app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_request.rb:111&gt;</td></tr>
<tr><td>rack.hijack?</td><td>true</td></tr>
<tr><td>rack.input</td><td>#&lt;StringIO:0x007fad0bc463e0&gt;</td></tr>
<tr><td>rack.logger</td><td>#&lt;Logger:0x007fad0b49af38&gt;</td></tr>
<tr><td>rack.multiprocess</td><td>true</td></tr>
<tr><td>rack.multithread</td><td>false</td></tr>
<tr><td>rack.request.cookie_hash</td><td>{}</td></tr>
<tr><td>rack.request.query_hash</td><td>{}</td></tr>
<tr><td>rack.request.query_string</td><td></td></tr>
<tr><td>rack.run_once</td><td>false</td></tr>
<tr><td>rack.session</td><td>#&lt;ActionDispatch::Request::Session:0x007fad10e3df18&gt;</td></tr>
<tr><td>rack.session.options</td><td>#&lt;ActionDispatch::Request::Session::Options:0x007fad10e3dec8&gt;</td></tr>
<tr><td>rack.url_scheme</td><td>http</td></tr>
<tr><td>rack.version</td><td>[1, 2]</td></tr>
<tr><td>warden</td><td>Warden::Proxy:70190644718900 @config={:default_scope=&gt;:user, :scope_defaults=&gt;{}, :default_strategies=&gt;{:user=&gt;[:rememberable, :database_authenticatable]}, :intercept_401=&gt;false, :failure_app=&gt;#&lt;Devise::Delegator:0x007fad10e31010&gt;}</td></tr>
<tr><td>Process</td><td>8</td></tr>
<tr><td>Server</td><td>ead3fc4b-56bf-4706-b5c7-5f9ce527af5c</td></tr>
</table>

<h2>Backtrace</h2>

<pre>
app/views/events/index.atom.builder:6:in `block in _app_views_events_index_atom_builder___543000240874566235_70190644209100&#39;
app/views/events/index.atom.builder:1:in `_app_views_events_index_atom_builder___543000240874566235_70190644209100&#39;
app/controllers/events_controller.rb:19:in `index&#39;
</pre>

<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Mar 28",1]}' title='{"runtimeerror":["Mar 28",1]}'/>
