### ISSUE TITLE
events#show (ActiveRecord::RecordNotFound) "ActiveRecord::RecordNotFound"

### ISSUE THREAD

**Issue by kugaevsky** [NNRUG/it52-rails#32]
<meta name="exception_notification_http">

<h2>ActiveRecord::RecordNotFound occurred in events</h2>

<pre>
ActiveRecord::RecordNotFound
app/controllers/events_controller.rb:74:in `set_event&#39;
</pre>

<h2>Request</h2>

<table class="table table-hover table-condensed">
<tr><td>URL</td><td>http://www.it52.info/events/undefined</td></tr>
<tr><td>IP address</td><td>91.211.128.216</td></tr>
<tr><td>Parameters</td><td>{&quot;action&quot;=&gt;&quot;show&quot;, &quot;controller&quot;=&gt;&quot;events&quot;, &quot;id&quot;=&gt;&quot;undefined&quot;}</td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2015-02-10 15:15:19 +0300</td></tr>
</table>

<h2>Session</h2>

<table class="table table-hover table-condensed">
<tr><td>session id</td><td>&quot;d3d4589be3be647169412554308af631&quot;</td></tr>
<tr><td>data</td><td>#&lt;ActionDispatch::Request::Session:0x007f42d64c8568 ...&gt;
</td></tr>
</table>

<h2>Environment</h2>

<table class="table table-hover table-condensed">
<tr><td>HTTP_ACCEPT</td><td>image/webp,*/*;q=0.8</td></tr>
<tr><td>HTTP_ACCEPT_ENCODING</td><td>gzip, deflate, sdch</td></tr>
<tr><td>HTTP_ACCEPT_LANGUAGE</td><td>ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4</td></tr>
<tr><td>HTTP_CONNECTION</td><td>close</td></tr>
<tr><td>HTTP_CONNECT_TIME</td><td>0</td></tr>
<tr><td>HTTP_COOKIE</td><td>_it52_rails_session=QTVld3RLNmQrSFRjU1ZDTFhvVUlPaUZNaERsL0ptd1NvYzdGWXRpR29jUHJKSkZlR2hnUzBkWG9pQUpNVThYYWFCb3BubVkzd3N6Qi9sV3p4RHVHS05qaExPWkdKSGhRRUpYbEV6YkV1eGdMbkw4Y2hESnFmV3NocmlBUG94M3piMU5tNjNJUk14dGJ1OGI2VlVuSHBRPT0tLUQybXcvdUR3QU1yaHc4Nms4N1RSUGc9PQ%3D%3D--f7966828b9962e9afab32feae2c03204563bea45; _gat=1; _ga=GA1.2.713907803.1423566624; _dc_gtm_UA-54446007-1=1</td></tr>
<tr><td>HTTP_HOST</td><td>www.it52.info</td></tr>
<tr><td>HTTP_REFERER</td><td>http://www.it52.info/events/2015-02-28-js-nn-1</td></tr>
<tr><td>HTTP_TOTAL_ROUTE_TIME</td><td>0</td></tr>
<tr><td>HTTP_USER_AGENT</td><td>Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36</td></tr>
<tr><td>HTTP_VERSION</td><td>HTTP/1.1</td></tr>
<tr><td>HTTP_VIA</td><td>1.1 vegur</td></tr>
<tr><td>HTTP_X_FORWARDED_FOR</td><td>91.211.128.216</td></tr>
<tr><td>HTTP_X_FORWARDED_PORT</td><td>80</td></tr>
<tr><td>HTTP_X_FORWARDED_PROTO</td><td>http</td></tr>
<tr><td>HTTP_X_REQUEST_ID</td><td>7b7db76c-f81d-4d96-8744-9fabb989a81e</td></tr>
<tr><td>HTTP_X_REQUEST_START</td><td>1423570518660</td></tr>
<tr><td>ORIGINAL_FULLPATH</td><td>/events/undefined</td></tr>
<tr><td>ORIGINAL_SCRIPT_NAME</td><td></td></tr>
<tr><td>PATH_INFO</td><td>/events/undefined</td></tr>
<tr><td>QUERY_STRING</td><td></td></tr>
<tr><td>REMOTE_ADDR</td><td>10.36.133.87</td></tr>
<tr><td>REQUEST_METHOD</td><td>GET</td></tr>
<tr><td>REQUEST_PATH</td><td>/events/undefined</td></tr>
<tr><td>REQUEST_URI</td><td>/events/undefined</td></tr>
<tr><td>ROUTES_69962533858860_SCRIPT_NAME</td><td></td></tr>
<tr><td>SCRIPT_NAME</td><td></td></tr>
<tr><td>SERVER_NAME</td><td>www.it52.info</td></tr>
<tr><td>SERVER_PORT</td><td>80</td></tr>
<tr><td>SERVER_PROTOCOL</td><td>HTTP/1.1</td></tr>
<tr><td>SERVER_SOFTWARE</td><td>Unicorn 4.8.3</td></tr>
<tr><td>action_controller.instance</td><td>events#show</td></tr>
<tr><td>action_dispatch.backtrace_cleaner</td><td>#&lt;Rails::BacktraceCleaner:0x007f42d6408830&gt;</td></tr>
<tr><td>action_dispatch.cookies</td><td>#&lt;ActionDispatch::Cookies::CookieJar:0x007f42d640b0d0&gt;</td></tr>
<tr><td>action_dispatch.cookies_serializer</td><td>json</td></tr>
<tr><td>action_dispatch.encrypted_cookie_salt</td><td>encrypted cookie</td></tr>
<tr><td>action_dispatch.encrypted_signed_cookie_salt</td><td>signed encrypted cookie</td></tr>
<tr><td>action_dispatch.http_auth_salt</td><td>http authentication</td></tr>
<tr><td>action_dispatch.key_generator</td><td>#&lt;ActiveSupport::CachingKeyGenerator:0x007f42d63ff758&gt;</td></tr>
<tr><td>action_dispatch.logger</td><td>#&lt;Logger:0x007f42d7e28b70&gt;</td></tr>
<tr><td>action_dispatch.parameter_filter</td><td>[:password]</td></tr>
<tr><td>action_dispatch.redirect_filter</td><td>[]</td></tr>
<tr><td>action_dispatch.remote_ip</td><td>91.211.128.216</td></tr>
<tr><td>action_dispatch.request.content_type</td><td></td></tr>
<tr><td>action_dispatch.request.formats</td><td>[#&lt;Mime::Type:0x007f42d445f0d8 @synonyms=[&quot;application/xhtml+xml&quot;], @symbol=:html, @string=&quot;text/html&quot;&gt;]</td></tr>
<tr><td>action_dispatch.request.parameters</td><td>{&quot;action&quot;=&gt;&quot;show&quot;, &quot;controller&quot;=&gt;&quot;events&quot;, &quot;id&quot;=&gt;&quot;undefined&quot;}</td></tr>
<tr><td>action_dispatch.request.path_parameters</td><td>{:action=&gt;&quot;show&quot;, :controller=&gt;&quot;events&quot;, :id=&gt;&quot;undefined&quot;}</td></tr>
<tr><td>action_dispatch.request.query_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.request_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.unsigned_session_cookie</td><td>{&quot;session_id&quot;=&gt;&quot;d3d4589be3be647169412554308af631&quot;, &quot;_csrf_token&quot;=&gt;&quot;AG6Riza3/BxqmT0BuVNB2DyzLGqWjcu5zYHIuDnHbQ4=&quot;}</td></tr>
<tr><td>action_dispatch.request_id</td><td>7b7db76c-f81d-4d96-8744-9fabb989a81e</td></tr>
<tr><td>action_dispatch.routes</td><td>#&lt;ActionDispatch::Routing::RouteSet:0x007f42d7f4dc58&gt;</td></tr>
<tr><td>action_dispatch.secret_key_base</td><td>&lt;%= ENV[&#39;secret_key_base&#39;] =&gt;</td></tr>
<tr><td>action_dispatch.secret_token</td><td></td></tr>
<tr><td>action_dispatch.show_detailed_exceptions</td><td>false</td></tr>
<tr><td>action_dispatch.show_exceptions</td><td>true</td></tr>
<tr><td>action_dispatch.signed_cookie_salt</td><td>signed cookie</td></tr>
<tr><td>newrelic.agent_hooks_before_fired</td><td>true</td></tr>
<tr><td>newrelic.captured_request</td><td>true</td></tr>
<tr><td>rack.errors</td><td>#&lt;IO:0x007f42d29f9540&gt;</td></tr>
<tr><td>rack.hijack</td><td>#&lt;Proc:0x007f42d64fc188@/app/vendor/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_request.rb:111&gt;</td></tr>
<tr><td>rack.hijack?</td><td>true</td></tr>
<tr><td>rack.input</td><td>#&lt;StringIO:0x007f42d3606d38&gt;</td></tr>
<tr><td>rack.logger</td><td>#&lt;Logger:0x007f42d3236b18&gt;</td></tr>
<tr><td>rack.multiprocess</td><td>true</td></tr>
<tr><td>rack.multithread</td><td>false</td></tr>
<tr><td>rack.request.cookie_hash</td><td>{&quot;_it52_rails_session&quot;=&gt;&quot;QTVld3RLNmQrSFRjU1ZDTFhvVUlPaUZNaERsL0ptd1NvYzdGWXRpR29jUHJKSkZlR2hnUzBkWG9pQUpNVThYYWFCb3BubVkzd3N6Qi9sV3p4RHVHS05qaExPWkdKSGhRRUpYbEV6YkV1eGdMbkw4Y2hESnFmV3NocmlBUG94M3piMU5tNjNJUk14dGJ1OGI2VlVuSHBRPT0tLUQybXcvdUR3QU1yaHc4Nms4N1RSUGc9PQ==--f7966828b9962e9afab32feae2c03204563bea45&quot;, &quot;_gat&quot;=&gt;&quot;1&quot;, &quot;_ga&quot;=&gt;&quot;GA1.2.713907803.1423566624&quot;, &quot;_dc_gtm_UA-54446007-1&quot;=&gt;&quot;1&quot;}</td></tr>
<tr><td>rack.request.cookie_string</td><td>_it52_rails_session=QTVld3RLNmQrSFRjU1ZDTFhvVUlPaUZNaERsL0ptd1NvYzdGWXRpR29jUHJKSkZlR2hnUzBkWG9pQUpNVThYYWFCb3BubVkzd3N6Qi9sV3p4RHVHS05qaExPWkdKSGhRRUpYbEV6YkV1eGdMbkw4Y2hESnFmV3NocmlBUG94M3piMU5tNjNJUk14dGJ1OGI2VlVuSHBRPT0tLUQybXcvdUR3QU1yaHc4Nms4N1RSUGc9PQ%3D%3D--f7966828b9962e9afab32feae2c03204563bea45; _gat=1; _ga=GA1.2.713907803.1423566624; _dc_gtm_UA-54446007-1=1</td></tr>
<tr><td>rack.request.query_hash</td><td>{}</td></tr>
<tr><td>rack.request.query_string</td><td></td></tr>
<tr><td>rack.run_once</td><td>false</td></tr>
<tr><td>rack.session</td><td>#&lt;ActionDispatch::Request::Session:0x007f42d64c8568&gt;</td></tr>
<tr><td>rack.session.options</td><td>#&lt;ActionDispatch::Request::Session::Options:0x007f42d64c84c8&gt;</td></tr>
<tr><td>rack.url_scheme</td><td>http</td></tr>
<tr><td>rack.version</td><td>[1, 2]</td></tr>
<tr><td>warden</td><td>Warden::Proxy:69962519928200 @config={:default_scope=&gt;:user, :scope_defaults=&gt;{}, :default_strategies=&gt;{:user=&gt;[:rememberable, :database_authenticatable]}, :intercept_401=&gt;false, :failure_app=&gt;#&lt;Devise::Delegator:0x007f42d85e7e60&gt;}</td></tr>
<tr><td>Process</td><td>8</td></tr>
<tr><td>Server</td><td>1591bfaa-9085-401c-b039-3873d453b442</td></tr>
</table>

<h2>Backtrace</h2>

<pre>
app/controllers/events_controller.rb:74:in `set_event&#39;
</pre>

<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=3&above-color=red&below-color=gray&width=5&limits=0,3&d=0,2,3,0,1,0,1' alt='{"runtimeerror":["Jun 29",2,"Jun 30",3,"Jul 02",1,"Jul 04",1]}' title='{"runtimeerror":["Jun 29",2,"Jun 30",3,"Jul 02",1,"Jul 04",1]}'/>

**Comment by kugaevsky** [comment]
<meta name="exception_notification_http">

<h2>ActiveRecord::RecordNotFound occurred in events</h2>

<pre>
ActiveRecord::RecordNotFound
app/controllers/events_controller.rb:121:in `set_event&#39;
</pre>

<h2>Request</h2>

<table class="table table-hover table-condensed">
<tr><td>URL</td><td>https://www.it52.info/events/production</td></tr>
<tr><td>IP address</td><td>46.4.32.75</td></tr>
<tr><td>Parameters</td><td>{&quot;controller&quot;=&gt;&quot;events&quot;, &quot;action&quot;=&gt;&quot;show&quot;, &quot;id&quot;=&gt;&quot;production&quot;}</td></tr>
<tr><td>Rails root</td><td>/app</td></tr>
<tr><td>Timestamp</td><td>2016-06-26 21:28:53 +0300</td></tr>
</table>

<h2>Session</h2>

<table class="table table-hover table-condensed">
<tr><td>session id</td><td>[FILTERED]</td></tr>
<tr><td>data</td><td>#&lt;ActionDispatch::Request::Session:0x7f80909b48b8 not yet loaded&gt;
</td></tr>
</table>

<h2>Environment</h2>

<table class="table table-hover table-condensed">
<tr><td>HTTP_ACCEPT</td><td>text/html,text/plain,text/xml,text/*,application/xml,application/xhtml+xml,application/rss+xml,application/atom+xml,application/rdf+xml,application/php,application/x-php,application/x-httpd-php</td></tr>
<tr><td>HTTP_ACCEPT_LANGUAGE</td><td>en</td></tr>
<tr><td>HTTP_CONNECTION</td><td>close</td></tr>
<tr><td>HTTP_CONNECT_TIME</td><td>1</td></tr>
<tr><td>HTTP_HOST</td><td>www.it52.info</td></tr>
<tr><td>HTTP_TOTAL_ROUTE_TIME</td><td>0</td></tr>
<tr><td>HTTP_USER_AGENT</td><td>Mozilla/5.0 (compatible; MJ12bot/v1.4.5; http://www.majestic12.co.uk/bot.php?+)</td></tr>
<tr><td>HTTP_VERSION</td><td>HTTP/1.1</td></tr>
<tr><td>HTTP_VIA</td><td>1.1 vegur</td></tr>
<tr><td>HTTP_X_FORWARDED_FOR</td><td>46.4.32.75</td></tr>
<tr><td>HTTP_X_FORWARDED_PORT</td><td>443</td></tr>
<tr><td>HTTP_X_FORWARDED_PROTO</td><td>https</td></tr>
<tr><td>HTTP_X_REQUEST_ID</td><td>3e438886-f5a4-4864-b75e-262beb0f7a52</td></tr>
<tr><td>HTTP_X_REQUEST_START</td><td>1466965733099</td></tr>
<tr><td>ORIGINAL_FULLPATH</td><td>/events/production</td></tr>
<tr><td>ORIGINAL_SCRIPT_NAME</td><td></td></tr>
<tr><td>PATH_INFO</td><td>/events/production</td></tr>
<tr><td>QUERY_STRING</td><td></td></tr>
<tr><td>REMOTE_ADDR</td><td>10.90.160.166</td></tr>
<tr><td>REQUEST_METHOD</td><td>GET</td></tr>
<tr><td>REQUEST_PATH</td><td>/events/production</td></tr>
<tr><td>REQUEST_URI</td><td>/events/production</td></tr>
<tr><td>ROUTES_70095063913380_SCRIPT_NAME</td><td></td></tr>
<tr><td>SCRIPT_NAME</td><td></td></tr>
<tr><td>SERVER_NAME</td><td>www.it52.info</td></tr>
<tr><td>SERVER_PORT</td><td>443</td></tr>
<tr><td>SERVER_PROTOCOL</td><td>HTTP/1.1</td></tr>
<tr><td>SERVER_SOFTWARE</td><td>Unicorn 5.1.0</td></tr>
<tr><td>action_controller.instance</td><td>events#show</td></tr>
<tr><td>action_dispatch.backtrace_cleaner</td><td>#&lt;Rails::BacktraceCleaner:0x007f8090bc1408&gt;</td></tr>
<tr><td>action_dispatch.cookies</td><td>#&lt;ActionDispatch::Cookies::CookieJar:0x007f809098a1a8&gt;</td></tr>
<tr><td>action_dispatch.cookies_digest</td><td></td></tr>
<tr><td>action_dispatch.cookies_serializer</td><td>json</td></tr>
<tr><td>action_dispatch.encrypted_cookie_salt</td><td>encrypted cookie</td></tr>
<tr><td>action_dispatch.encrypted_signed_cookie_salt</td><td>signed encrypted cookie</td></tr>
<tr><td>action_dispatch.http_auth_salt</td><td>http authentication</td></tr>
<tr><td>action_dispatch.key_generator</td><td>#&lt;ActiveSupport::CachingKeyGenerator:0x007f8091926ad0&gt;</td></tr>
<tr><td>action_dispatch.logger</td><td>#&lt;RailsStdoutLogging::StdoutLogger:0x007f808ddcec30&gt;</td></tr>
<tr><td>action_dispatch.parameter_filter</td><td>[:password]</td></tr>
<tr><td>action_dispatch.redirect_filter</td><td>[]</td></tr>
<tr><td>action_dispatch.remote_ip</td><td>46.4.32.75</td></tr>
<tr><td>action_dispatch.request.accepts</td><td>[#&lt;Mime::Type:0x007f808f0eefe0 @synonyms=[&quot;application/xhtml+xml&quot;], @symbol=:html, @string=&quot;text/html&quot;, @hash=35278917444971371&gt;, #&lt;Mime::Type:0x007f808f0eece8 @synonyms=[], @symbol=:text, @string=&quot;text/plain&quot;, @hash=-1499345606669101364&gt;, #&lt;Mime::Type:0x007f808f0ee978 @synonyms=[&quot;application/javascript&quot;, &quot;application/x-javascript&quot;], @symbol=:js, @string=&quot;text/javascript&quot;, @hash=3798514282678516980&gt;, #&lt;Mime::Type:0x007f808f0ee6d0 @synonyms=[], @symbol=:css, @string=&quot;text/css&quot;, @hash=240731979484880997&gt;, #&lt;Mime::Type:0x007f808f0ee3d8 @synonyms=[], @symbol=:ics, @string=&quot;text/calendar&quot;, @hash=-70351702312258882&gt;, #&lt;Mime::Type:0x007f808f0ee0e0 @synonyms=[], @symbol=:csv, @string=&quot;text/csv&quot;, @hash=-2328363236365028556&gt;, #&lt;Mime::Type:0x007f808f0edde8 @synonyms=[], @symbol=:vcf, @string=&quot;text/vcard&quot;, @hash=-2935716109092076956&gt;, #&lt;Mime::Type:0x007f808db73508 @synonyms=[&quot;text/yaml&quot;], @symbol=:yaml, @string=&quot;application/x-yaml&quot;, @hash=-4490809395360420779&gt;, #&lt;Mime::Type:0x007f808db721f8 @synonyms=[&quot;text/x-json&quot;, &quot;application/jsonrequest&quot;], @symbol=:json, @string=&quot;application/json&quot;, @hash=3919303944314985382&gt;, #&lt;Mime::Type:0x007f808f0ec678 @synonyms=[&quot;text/xml&quot;, &quot;application/x-xml&quot;], @symbol=:xml, @string=&quot;application/xml&quot;, @hash=128042249164996739&gt;, #&lt;Mime::Type:0x007f808f0ec330 @synonyms=[], @symbol=:rss, @string=&quot;application/rss+xml&quot;, @hash=-661252512549417200&gt;, #&lt;Mime::Type:0x007f808f0ec038 @synonyms=[], @symbol=:atom, @string=&quot;application/atom+xml&quot;, @hash=-678960849163708366&gt;, #&lt;Mime::Type:0x007f809098bd78 @synonyms=[], @symbol=nil, @string=&quot;application/rdf+xml&quot;, @hash=245227530763711285&gt;, #&lt;Mime::Type:0x007f809098bd00 @synonyms=[], @symbol=nil, @string=&quot;application/php&quot;, @hash=-3385075502539076226&gt;, #&lt;Mime::Type:0x007f809098bc60 @synonyms=[], @symbol=nil, @string=&quot;application/x-php&quot;, @hash=3420258935170876147&gt;, #&lt;Mime::Type:0x007f809098bbe8 @synonyms=[], @symbol=nil, @string=&quot;application/x-httpd-php&quot;, @hash=-418246620164462075&gt;]</td></tr>
<tr><td>action_dispatch.request.content_type</td><td></td></tr>
<tr><td>action_dispatch.request.formats</td><td>[#&lt;Mime::Type:0x007f808f0eefe0 @synonyms=[&quot;application/xhtml+xml&quot;], @symbol=:html, @string=&quot;text/html&quot;, @hash=35278917444971371&gt;, #&lt;Mime::Type:0x007f808f0eece8 @synonyms=[], @symbol=:text, @string=&quot;text/plain&quot;, @hash=-1499345606669101364&gt;, #&lt;Mime::Type:0x007f808f0ee978 @synonyms=[&quot;application/javascript&quot;, &quot;application/x-javascript&quot;], @symbol=:js, @string=&quot;text/javascript&quot;, @hash=3798514282678516980&gt;, #&lt;Mime::Type:0x007f808f0ee6d0 @synonyms=[], @symbol=:css, @string=&quot;text/css&quot;, @hash=240731979484880997&gt;, #&lt;Mime::Type:0x007f808f0ee3d8 @synonyms=[], @symbol=:ics, @string=&quot;text/calendar&quot;, @hash=-70351702312258882&gt;, #&lt;Mime::Type:0x007f808f0ee0e0 @synonyms=[], @symbol=:csv, @string=&quot;text/csv&quot;, @hash=-2328363236365028556&gt;, #&lt;Mime::Type:0x007f808f0edde8 @synonyms=[], @symbol=:vcf, @string=&quot;text/vcard&quot;, @hash=-2935716109092076956&gt;, #&lt;Mime::Type:0x007f808db73508 @synonyms=[&quot;text/yaml&quot;], @symbol=:yaml, @string=&quot;application/x-yaml&quot;, @hash=-4490809395360420779&gt;, #&lt;Mime::Type:0x007f808db721f8 @synonyms=[&quot;text/x-json&quot;, &quot;application/jsonrequest&quot;], @symbol=:json, @string=&quot;application/json&quot;, @hash=3919303944314985382&gt;, #&lt;Mime::Type:0x007f808f0ec678 @synonyms=[&quot;text/xml&quot;, &quot;application/x-xml&quot;], @symbol=:xml, @string=&quot;application/xml&quot;, @hash=128042249164996739&gt;, #&lt;Mime::Type:0x007f808f0ec330 @synonyms=[], @symbol=:rss, @string=&quot;application/rss+xml&quot;, @hash=-661252512549417200&gt;, #&lt;Mime::Type:0x007f808f0ec038 @synonyms=[], @symbol=:atom, @string=&quot;application/atom+xml&quot;, @hash=-678960849163708366&gt;, #&lt;Mime::Type:0x007f809098bd78 @synonyms=[], @symbol=nil, @string=&quot;application/rdf+xml&quot;, @hash=245227530763711285&gt;, #&lt;Mime::Type:0x007f809098bd00 @synonyms=[], @symbol=nil, @string=&quot;application/php&quot;, @hash=-3385075502539076226&gt;, #&lt;Mime::Type:0x007f809098bc60 @synonyms=[], @symbol=nil, @string=&quot;application/x-php&quot;, @hash=3420258935170876147&gt;, #&lt;Mime::Type:0x007f809098bbe8 @synonyms=[], @symbol=nil, @string=&quot;application/x-httpd-php&quot;, @hash=-418246620164462075&gt;]</td></tr>
<tr><td>action_dispatch.request.parameters</td><td>{&quot;controller&quot;=&gt;&quot;events&quot;, &quot;action&quot;=&gt;&quot;show&quot;, &quot;id&quot;=&gt;&quot;production&quot;}</td></tr>
<tr><td>action_dispatch.request.path_parameters</td><td>{:controller=&gt;&quot;events&quot;, :action=&gt;&quot;show&quot;, :id=&gt;&quot;production&quot;}</td></tr>
<tr><td>action_dispatch.request.query_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.request_parameters</td><td>{}</td></tr>
<tr><td>action_dispatch.request.unsigned_session_cookie</td><td>{}</td></tr>
<tr><td>action_dispatch.request_id</td><td>3e438886-f5a4-4864-b75e-262beb0f7a52</td></tr>
<tr><td>action_dispatch.routes</td><td>#&lt;ActionDispatch::Routing::RouteSet:0x007f808ec52748&gt;</td></tr>
<tr><td>action_dispatch.secret_key_base</td><td>&lt;%= ENV[&#39;secret_key_base&#39;] =&gt;</td></tr>
<tr><td>action_dispatch.secret_token</td><td></td></tr>
<tr><td>action_dispatch.show_detailed_exceptions</td><td>false</td></tr>
<tr><td>action_dispatch.show_exceptions</td><td>true</td></tr>
<tr><td>action_dispatch.signed_cookie_salt</td><td>signed cookie</td></tr>
<tr><td>newrelic.transaction_started</td><td>true</td></tr>
<tr><td>rack.errors</td><td>#&lt;IO:0x007f808c899b08&gt;</td></tr>
<tr><td>rack.hijack</td><td>#&lt;Unicorn::HttpParser:0x007f808d3155c8&gt;</td></tr>
<tr><td>rack.hijack?</td><td>true</td></tr>
<tr><td>rack.input</td><td>#&lt;StringIO:0x007f808d59a820&gt;</td></tr>
<tr><td>rack.logger</td><td>#&lt;Logger:0x007f808d4b7ac0&gt;</td></tr>
<tr><td>rack.multiprocess</td><td>true</td></tr>
<tr><td>rack.multithread</td><td>false</td></tr>
<tr><td>rack.request.cookie_hash</td><td>{}</td></tr>
<tr><td>rack.request.query_hash</td><td>{}</td></tr>
<tr><td>rack.request.query_string</td><td></td></tr>
<tr><td>rack.run_once</td><td>false</td></tr>
<tr><td>rack.session</td><td>#&lt;ActionDispatch::Request::Session:0x007f80909b48b8&gt;</td></tr>
<tr><td>rack.session.options</td><td>#&lt;ActionDispatch::Request::Session::Options:0x007f80909b4840&gt;</td></tr>
<tr><td>rack.url_scheme</td><td>https</td></tr>
<tr><td>rack.version</td><td>[1, 2]</td></tr>
<tr><td>unicorn.socket</td><td>#&lt;Kgio::Socket:0x007f80909e04b8&gt;</td></tr>
<tr><td>warden</td><td>Warden::Proxy:70095079317980 @config={:default_scope=&gt;:user, :scope_defaults=&gt;{}, :default_strategies=&gt;{:user=&gt;[:rememberable, :database_authenticatable]}, :intercept_401=&gt;false, :failure_app=&gt;#&lt;Devise::Delegator:0x007f809136ae98&gt;}</td></tr>
<tr><td>Process</td><td>9</td></tr>
<tr><td>Server</td><td>6e137c18-3023-4372-afe2-84e8bfc3e038</td></tr>
</table>

<h2>Backtrace</h2>

<pre>
app/controllers/events_controller.rb:121:in `set_event&#39;
</pre>

<br/>
<img src='http://sparklines-bitworking.appspot.com/spark.cgi?type=impulse&height=40&upper=1&above-color=red&below-color=gray&width=5&limits=0,1&d=0,0,0,0,0,0,1' alt='{"runtimeerror":["Jun 26",1]}' title='{"runtimeerror":["Jun 26",1]}'/>
